name: "CloudFlare DNS: Delete Record"
description: "Delete DNS Record from CloudFlare"
author: "Bluesboy"

inputs:
  name:
    description: "DNS record name"
    required: true
  token:
    description: "CloudFlare API Token"
    required: true
  zone:
    description: "CloudFlare Zone ID"
    required: true

runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "delete"
  color: "orange"
